#!/usr/bin/env sh
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition

# Configure scripting addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Bar
# yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m config external_bar main:35:0

# Tiling
yabai -m config layout bsp
yabai -m config window_placement second_child # spawns windows right/bottom

# Gaps
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 06

# Mouse
yabai -m config mouse_modifier alt # set mouse modifer to ALT
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse autoraise 

# Splits
yabai -m config split_ratio 0.50
yabai -m config split_type auto

# Window
yabai -m config window_zoom_persist on
yabai -m config window_topmost off
yabai -m config window_shadow off
yabai -m config window_animation_duration 0.0
yabai -m config window_animation_frame_rate 120
yabai -m config insert_feedback_color 0xffd75f5f
yabai -m config active_window_border_color 0xff775759
yabai -m config normal_window_border_color 0xff555555
yabai -m config window_border_width 4
yabai -m config window_border_radius 12
yabai -m config window_border_blur off
yabai -m config window_border_hidpi on
yabai -m config window_border off
yabai -m config auto_balance off

# Window opacity
yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.0
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.90

# Float windows
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^KakaoTalk$" manage=off

# Debug
# If running through brew services log files are located
# HOMEBREW_PREFIX/var/log/yabai/
yabai -m config debug_output off
